clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    cd %APPVEYOR_BUILD_FOLDER%
    git checkout -qf %APPVEYOR_REPO_COMMIT%
    git submodule update --init --recursive

before_build:
  - ps: .\build\restore-packages.ps1

version: '0.0.0.{build}'
