// Copyright (c) Microsoft Open Technologies, Inc. All rights reserved. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using RouteData = Microsoft.AspNetCore.Routing.RouteData;

namespace Xcst.Web.Mvc;

public class ViewContext {

   HttpContext?
   _httpContext;

   ActionContext?
   _actionContext;

   FormContext
   _formContext = new();

   public HttpContext
   HttpContext {
#pragma warning disable CS8603
      get => _httpContext;
#pragma warning restore CS8603
      set => _httpContext = value;
   }

   public ActionContext
   ActionContext => _actionContext ??= new() {
      HttpContext = HttpContext,
      RouteData = new RouteData()
   };

   public virtual FormContext
   FormContext {
      get => _formContext;
      set => _formContext = value ?? throw new ArgumentNullException(nameof(value));
   }

   public virtual bool
   ClientValidationEnabled { get; set; } = true;

   /// <summary>
   /// Element name used to wrap a top-level message generated by
   /// <code>a:validation-message</code>.
   /// </summary>
   public virtual string
   ValidationMessageElement { get; set; } = "span";

   // parameterless constructor used for mocking
   public
   ViewContext() { }

   public
   ViewContext(HttpContext httpContext) {

      ArgumentNullException.ThrowIfNull(httpContext);

      _httpContext = httpContext;
   }

   public
   ViewContext(ViewContext viewContext) {

      ArgumentNullException.ThrowIfNull(viewContext);

      _httpContext = viewContext._httpContext;
      _actionContext = viewContext._actionContext;

      this.FormContext = viewContext.FormContext;
      this.ClientValidationEnabled = viewContext.ClientValidationEnabled;
      this.ValidationMessageElement = viewContext.ValidationMessageElement;
   }

   internal FormContext?
   GetFormContextForClientValidation() =>
      (this.ClientValidationEnabled) ? this.FormContext : null;
}

public class FormContext {

   readonly Dictionary<string, bool>
   _renderedFields = new();

   public bool
   RenderedField(string fieldName) {

      _renderedFields.TryGetValue(fieldName, out var result);
      return result;
   }

   public void
   RenderedField(string fieldName, bool value) =>
      _renderedFields[fieldName] = value;
}
