// Copyright 2015 Max Toro Q.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;

namespace Xcst.Web.Mvc;

public sealed class ViewOptions {

   public bool
   ClientValidationEnabled { get; set; } = true;

   public string?
   EditorGroupCssClass { get; set; }

   public string?
   DisplayGroupCssClass { get; set; }

   public Func<string, string?, string?>?
   EditorCssClass { get; set; }

   public Func<bool, string?>?
   LabelCssClass { get; set; }

   public Func<string, ViewContext, XcstViewPage?>?
   EditorTemplateFactory { get; set; }

   public Func<string, ViewContext, XcstViewPage?>?
   DisplayTemplateFactory { get; set; }

   public string
   IdAttributeDotReplacement { get; set; } = "_";

   /// <summary>
   /// Element name used to wrap a top-level message generated by
   /// <code>a:validation-message</code>.
   /// </summary>
   public string
   ValidationMessageElement { get; set; } = "span";
}
