// Copyright (c) Microsoft Open Technologies, Inc. All rights reserved. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using Microsoft.AspNetCore.Http;
using Xcst.Runtime;
using RouteData = Microsoft.AspNetCore.Routing.RouteData;

namespace Xcst.Web.Mvc;

public class ViewContext {

   ActionContext?
   _actionContext;

   FormContext?
   _formContext;

   string?
   _htmlFieldPrefix;

   object?
   _formattedModelValue;

   IDictionary<string, object?>?
   _htmlAttributes;

   IList<string>?
   _membersNames;

   IDictionary<string, IEnumerable<SelectListItem>>?
   _membersOptions;

   IDictionary<string, object?>?
   _viewParameters;

   HashSet<object>?
   _visitedObjects;

   public HttpContext
   HttpContext { get; }

   public IXcstPackage?
   CurrentPackage { get; }

   public ActionContext
   ActionContext {
      get => _actionContext ??= new() {
         HttpContext = HttpContext,
         RouteData = new RouteData(),
      };
      private set => _actionContext = value;
   }

   [AllowNull]
   public FormContext
   FormContext {
      get => _formContext ??= new();
      set => _formContext = value;
   }

   public FormMethod
   FormMethod { get; set; }

   public CultureInfo
   FormCulture {
      get => (FormMethod == FormMethod.Get) ?
         CultureInfo.InvariantCulture
         : CultureInfo.CurrentCulture;
   }

   public bool
   ClientValidationEnabled { get; set; }

   /// <summary>
   /// Element name used to wrap a top-level message generated by
   /// <code>a:validation-message</code>.
   /// </summary>
   public string
   ValidationMessageElement { get; set; }

   [AllowNull]
   public string
   HtmlFieldPrefix {
      get => _htmlFieldPrefix ?? String.Empty;
      set => _htmlFieldPrefix = value;
   }

   [AllowNull]
   public object
   FormattedModelValue {
      get => _formattedModelValue ?? String.Empty;
      set => _formattedModelValue = value;
   }

   [AllowNull]
   public IDictionary<string, object?>
   HtmlAttributes {
      get => _htmlAttributes ??= new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
      set => _htmlAttributes = value;
   }

   [AllowNull]
   internal IList<string>
   MembersNames {
      get => _membersNames ?? Array.Empty<string>();
      set => _membersNames = value;
   }

   [AllowNull]
   public IDictionary<string, IEnumerable<SelectListItem>>
   MembersOptions {
      get => _membersOptions ??= new Dictionary<string, IEnumerable<SelectListItem>>();
      set => _membersOptions = value;
   }

   internal Action<HtmlHelper, ISequenceWriter<object?>>?
   MemberTemplate { get; set; }

   internal string?
   ViewName { get; set; }

   [AllowNull]
   internal IDictionary<string, object?>
   ViewParameters {
      get => _viewParameters ??= new Dictionary<string, object?>();
      set => _viewParameters = value;
   }

   // DDB #224750 - Keep a collection of visited objects to prevent infinite recursion

   [AllowNull]
   internal HashSet<object>
   VisitedObjects {
      get => _visitedObjects ??= new();
      set => _visitedObjects = value;
   }

   public int
   TemplateDepth => VisitedObjects.Count;

   public
   ViewContext(HttpContext httpContext, IXcstPackage? currentPackage) {

      ArgumentNullException.ThrowIfNull(httpContext);

      this.HttpContext = httpContext;
      this.CurrentPackage = currentPackage;

      this.FormContext = new FormContext();
      this.FormMethod = FormMethod.Post;
      this.ClientValidationEnabled = true;
      this.ValidationMessageElement = "span";
   }

   public
   ViewContext(ViewContext viewContext)
      : this(viewContext, null, null) { }

   public
   ViewContext(ViewContext viewContext, HttpContext? httpContext)
      : this(viewContext, httpContext, null) { }

   public
   ViewContext(ViewContext viewContext, HttpContext? httpContext, IXcstPackage? currentPackage) {

      ArgumentNullException.ThrowIfNull(viewContext);

      this.HttpContext = httpContext ?? viewContext.HttpContext;
      this.CurrentPackage = currentPackage ?? viewContext.CurrentPackage;
      this.ActionContext = viewContext.ActionContext;

      // FormContext must be shared, not copied
      this.FormContext = viewContext.FormContext;

      this.FormMethod = viewContext.FormMethod;
      this.ClientValidationEnabled = viewContext.ClientValidationEnabled;
      this.ValidationMessageElement = viewContext.ValidationMessageElement;

      _htmlFieldPrefix = viewContext._htmlFieldPrefix;

      if (viewContext._htmlAttributes is { Count: > 0 } htmlAttribs) {
         _htmlAttributes = new CopyOnWriteDictionary<string, object?>(htmlAttribs, StringComparer.OrdinalIgnoreCase);
      }

      if (viewContext._membersOptions is { Count: > 0 } memberOpts) {
         _membersOptions = new CopyOnWriteDictionary<string, IEnumerable<SelectListItem>>(memberOpts, EqualityComparer<string>.Default);
      }

      this.MemberTemplate = viewContext.MemberTemplate;

      if (viewContext._viewParameters is { Count: > 0 } viewParams) {
         _viewParameters = new CopyOnWriteDictionary<string, object?>(viewParams, EqualityComparer<string>.Default);
      }

      if (viewContext._visitedObjects is { Count: > 0 } visitedObjs) {
         _visitedObjects = new HashSet<object>(visitedObjs);
      }
   }

   internal FormContext?
   GetFormContextForClientValidation() =>
      (this.ClientValidationEnabled) ? this.FormContext : null;

   internal void
   SetFormMethodString(string formMethod) {

      ArgumentException.ThrowIfNullOrEmpty(formMethod);

      this.FormMethod = formMethod.ToUpperInvariant() switch {
         "GET" => FormMethod.Get,
         _ => FormMethod.Post,
      };
   }

   public void
   MergeHtmlAttributes(object? htmlAttributes) {

      if (htmlAttributes is null) {
         return;
      }

      var dict = htmlAttributes as IDictionary<string, object?>
         ?? HtmlHelper.AnonymousObjectToHtmlAttributes(htmlAttributes);

      foreach (var kvp in dict) {

         if (StringComparer.OrdinalIgnoreCase.Equals(kvp.Key, "class")) {
            HtmlAttributeDictionary.AddClass(this.HtmlAttributes, kvp.Value);
            continue;
         }

         this.HtmlAttributes[kvp.Key] = kvp.Value;
      }
   }

   internal IEnumerable<SelectListItem>?
   OptionsForModel() {

      if (_membersOptions?.TryGetValue(this.HtmlFieldPrefix, out var value) == true) {
         return value;
      }

      return null;
   }

   internal bool
   Visited(ModelExplorer modelExplorer) =>
      this.VisitedObjects.Contains(modelExplorer.Model ?? modelExplorer.Metadata.ModelType);
}

public enum FormMethod {
   Get,
   Post,
}

public class FormContext {

   readonly Dictionary<string, bool>
   _renderedFields = new();

   public bool
   RenderedField(string fieldName) {

      _renderedFields.TryGetValue(fieldName, out var result);
      return result;
   }

   public void
   RenderedField(string fieldName, bool value) =>
      _renderedFields[fieldName] = value;
}
